import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-dialysis-esrd-bundle-reimbursement-recovery",
  "engine": "recovery",
  "title": "Dialysis ESRD Bundle Reimbursement Recovery",
  "shortTitle": "Dialysis ESRD Bundle Reimbursement Recovery",
  "tagline": "Recalculate ESRD bundled payments, training adjustments, comorbid factors, and outlier reimbursement at treatment level.",
  "industry": "Renal Revenue Integrity",
  "buyer": "Dialysis organizations and renal practices",
  "uiPort": 4651,
  "apiPort": 5651,
  "accent": "#4f46e5",
  "currency": "USD",
  "primaryOutcome": "Dialysis ESRD Bundle Reimbursement Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect patient eligibility, ESRD PPS rates, treatments, labs, drugs, comorbidities, onset adjustments, training, outliers, claims, and remittances in one accountable workflow. Recalculate ESRD bundled payments, training adjustments, comorbid factors, and outlier reimbursement at treatment level.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Dialysis ESRD Bundle Reimbursement Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("patient-eligibility-registry","DEB01","Patient eligibility registry","Execute patient eligibility registry using patient eligibility, ESRD PPS rates, treatments, labs, drugs, comorbidities, onset adjustments, training, outliers, claims, and remittances.","Produce a governed patient eligibility registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Dialysis Treatment","text","Facility / Dialysis Treatment · Standard Case"],["caseReference","Patient eligibility registry Reference","text","DEB01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",617500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",747175],["domainDriver","Treatment Modality","select","In-center HD",["In-center HD","Home HD","Peritoneal dialysis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Patient eligibility registry case","Treatment ingestion case","ESRD base rate library case","Wage index adjustment case","Low-volume adjustment case"]}),
feature("treatment-ingestion","DEB02","Treatment ingestion","Execute treatment ingestion using patient eligibility, ESRD PPS rates, treatments, labs, drugs, comorbidities, onset adjustments, training, outliers, claims, and remittances.","Produce a governed treatment ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Dialysis Treatment","text","Facility / Dialysis Treatment · Standard Case"],["caseReference","Treatment ingestion Reference","text","DEB02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",617500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",747175],["domainDriver","Treatment Modality","select","In-center HD",["In-center HD","Home HD","Peritoneal dialysis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Patient eligibility registry case","Treatment ingestion case","ESRD base rate library case","Wage index adjustment case","Low-volume adjustment case"]}),
feature("esrd-base-rate-library","DEB03","ESRD base rate library","Execute esrd base rate library using patient eligibility, ESRD PPS rates, treatments, labs, drugs, comorbidities, onset adjustments, training, outliers, claims, and remittances.","Produce a governed esrd base rate library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Dialysis Treatment","text","Facility / Dialysis Treatment · Standard Case"],["caseReference","ESRD base rate library Reference","text","DEB03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",617500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",747175],["domainDriver","Treatment Modality","select","In-center HD",["In-center HD","Home HD","Peritoneal dialysis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Patient eligibility registry case","Treatment ingestion case","ESRD base rate library case","Wage index adjustment case","Low-volume adjustment case"]}),
feature("wage-index-adjustment","DEB04","Wage index adjustment","Execute wage index adjustment using patient eligibility, ESRD PPS rates, treatments, labs, drugs, comorbidities, onset adjustments, training, outliers, claims, and remittances.","Produce a governed wage index adjustment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Dialysis Treatment","text","Facility / Dialysis Treatment · Standard Case"],["caseReference","Wage index adjustment Reference","text","DEB04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",617500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",747175],["domainDriver","Treatment Modality","select","In-center HD",["In-center HD","Home HD","Peritoneal dialysis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Patient eligibility registry case","Treatment ingestion case","ESRD base rate library case","Wage index adjustment case","Low-volume adjustment case"]}),
feature("low-volume-adjustment","DEB05","Low-volume adjustment","Execute low-volume adjustment using patient eligibility, ESRD PPS rates, treatments, labs, drugs, comorbidities, onset adjustments, training, outliers, claims, and remittances.","Produce a governed low-volume adjustment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Dialysis Treatment","text","Facility / Dialysis Treatment · Standard Case"],["caseReference","Low-volume adjustment Reference","text","DEB05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",617500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",747175],["domainDriver","Treatment Modality","select","In-center HD",["In-center HD","Home HD","Peritoneal dialysis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Patient eligibility registry case","Treatment ingestion case","ESRD base rate library case","Wage index adjustment case","Low-volume adjustment case"]}),
feature("rural-adjustment","DEB06","Rural adjustment","Execute rural adjustment using patient eligibility, ESRD PPS rates, treatments, labs, drugs, comorbidities, onset adjustments, training, outliers, claims, and remittances.","Produce a governed rural adjustment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Dialysis Treatment","text","Facility / Dialysis Treatment · Standard Case"],["caseReference","Rural adjustment Reference","text","DEB06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",617500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",747175],["domainDriver","Treatment Modality","select","In-center HD",["In-center HD","Home HD","Peritoneal dialysis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Patient eligibility registry case","Treatment ingestion case","ESRD base rate library case","Wage index adjustment case","Low-volume adjustment case"]}),
feature("onset-adjustment","DEB07","Onset adjustment","Execute onset adjustment using patient eligibility, ESRD PPS rates, treatments, labs, drugs, comorbidities, onset adjustments, training, outliers, claims, and remittances.","Produce a governed onset adjustment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Dialysis Treatment","text","Facility / Dialysis Treatment · Standard Case"],["caseReference","Onset adjustment Reference","text","DEB07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",617500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",747175],["domainDriver","Treatment Modality","select","In-center HD",["In-center HD","Home HD","Peritoneal dialysis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Patient eligibility registry case","Treatment ingestion case","ESRD base rate library case","Wage index adjustment case","Low-volume adjustment case"]}),
feature("comorbidity-adjustment","DEB08","Comorbidity adjustment","Execute comorbidity adjustment using patient eligibility, ESRD PPS rates, treatments, labs, drugs, comorbidities, onset adjustments, training, outliers, claims, and remittances.","Produce a governed comorbidity adjustment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Dialysis Treatment","text","Facility / Dialysis Treatment · Standard Case"],["caseReference","Comorbidity adjustment Reference","text","DEB08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",617500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",747175],["domainDriver","Treatment Modality","select","In-center HD",["In-center HD","Home HD","Peritoneal dialysis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Patient eligibility registry case","Treatment ingestion case","ESRD base rate library case","Wage index adjustment case","Low-volume adjustment case"]}),
feature("training-add-on-calculation","DEB09","Training add-on calculation","Execute training add-on calculation using patient eligibility, ESRD PPS rates, treatments, labs, drugs, comorbidities, onset adjustments, training, outliers, claims, and remittances.","Produce a governed training add-on calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Dialysis Treatment","text","Facility / Dialysis Treatment · Standard Case"],["caseReference","Training add-on calculation Reference","text","DEB09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",617500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",747175],["domainDriver","Treatment Modality","select","In-center HD",["In-center HD","Home HD","Peritoneal dialysis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Patient eligibility registry case","Treatment ingestion case","ESRD base rate library case","Wage index adjustment case","Low-volume adjustment case"]}),
feature("tdapa-treatment","DEB10","TDAPA treatment","Execute tdapa treatment using patient eligibility, ESRD PPS rates, treatments, labs, drugs, comorbidities, onset adjustments, training, outliers, claims, and remittances.","Produce a governed tdapa treatment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Dialysis Treatment","text","Facility / Dialysis Treatment · Standard Case"],["caseReference","TDAPA treatment Reference","text","DEB10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",617500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",747175],["domainDriver","Treatment Modality","select","In-center HD",["In-center HD","Home HD","Peritoneal dialysis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Patient eligibility registry case","Treatment ingestion case","ESRD base rate library case","Wage index adjustment case","Low-volume adjustment case"]}),
feature("outlier-service-calculation","DEB11","Outlier service calculation","Execute outlier service calculation using patient eligibility, ESRD PPS rates, treatments, labs, drugs, comorbidities, onset adjustments, training, outliers, claims, and remittances.","Produce a governed outlier service calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Dialysis Treatment","text","Facility / Dialysis Treatment · Standard Case"],["caseReference","Outlier service calculation Reference","text","DEB11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",617500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",747175],["domainDriver","Treatment Modality","select","In-center HD",["In-center HD","Home HD","Peritoneal dialysis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Patient eligibility registry case","Treatment ingestion case","ESRD base rate library case","Wage index adjustment case","Low-volume adjustment case"]}),
feature("missing-treatment-detection","DEB12","Missing treatment detection","Execute missing treatment detection using patient eligibility, ESRD PPS rates, treatments, labs, drugs, comorbidities, onset adjustments, training, outliers, claims, and remittances.","Produce a governed missing treatment detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Dialysis Treatment","text","Facility / Dialysis Treatment · Standard Case"],["caseReference","Missing treatment detection Reference","text","DEB12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",617500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",747175],["domainDriver","Treatment Modality","select","In-center HD",["In-center HD","Home HD","Peritoneal dialysis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Patient eligibility registry case","Treatment ingestion case","ESRD base rate library case","Wage index adjustment case","Low-volume adjustment case"]}),
feature("claim-reconciliation","DEB13","Claim reconciliation","Execute claim reconciliation using patient eligibility, ESRD PPS rates, treatments, labs, drugs, comorbidities, onset adjustments, training, outliers, claims, and remittances.","Produce a governed claim reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Dialysis Treatment","text","Facility / Dialysis Treatment · Standard Case"],["caseReference","Claim reconciliation Reference","text","DEB13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",617500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",747175],["domainDriver","Treatment Modality","select","In-center HD",["In-center HD","Home HD","Peritoneal dialysis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Patient eligibility registry case","Treatment ingestion case","ESRD base rate library case","Wage index adjustment case","Low-volume adjustment case"]}),
feature("appeal-package-generation","DEB14","Appeal package generation","Execute appeal package generation using patient eligibility, ESRD PPS rates, treatments, labs, drugs, comorbidities, onset adjustments, training, outliers, claims, and remittances.","Produce a governed appeal package generation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Dialysis Treatment","text","Facility / Dialysis Treatment · Standard Case"],["caseReference","Appeal package generation Reference","text","DEB14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",617500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",747175],["domainDriver","Treatment Modality","select","In-center HD",["In-center HD","Home HD","Peritoneal dialysis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Patient eligibility registry case","Treatment ingestion case","ESRD base rate library case","Wage index adjustment case","Low-volume adjustment case"]}),
feature("facility-modality-analytics","DEB15","Facility modality analytics","Execute facility modality analytics using patient eligibility, ESRD PPS rates, treatments, labs, drugs, comorbidities, onset adjustments, training, outliers, claims, and remittances.","Produce a governed facility modality analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Dialysis Treatment","text","Facility / Dialysis Treatment · Standard Case"],["caseReference","Facility modality analytics Reference","text","DEB15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",617500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",747175],["domainDriver","Treatment Modality","select","In-center HD",["In-center HD","Home HD","Peritoneal dialysis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Patient eligibility registry case","Treatment ingestion case","ESRD base rate library case","Wage index adjustment case","Low-volume adjustment case"]})
]);
